server:
  port: 8080
spring:
  shardingsphere:
    datasource:
      names:
        master,slave
      # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.5.101:3306/reggie?characterEncoding=utf-8&useSSL=false
        username: root
        password: 491001
      # 从数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.5.102:3306/reggie?characterEncoding=utf-8&useSSL=false
        username: root
        password: 491001
    masterslave:
      # 读写分离配置
      load-balance-algorithm-type: round_robin #轮询
      # 最终的数据源名称
      name: dataSource
      # 主库数据源名称
      master-data-source-name: master
      # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names: slave
    props:
      sql:
        show: true #开启SQL显示，默认false
  main:
    allow-bean-definition-overriding: true
  # redis缓存
  redis:
    host: 192.168.5.100
    port: 6379
    password: 491001
    database: 0
  cache:
    redis:
      time-to-live: 1800000 #设置缓存数据的过期时间



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射 address_book--->AddressBook,默认开启
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id
# 文件上传位置
file:
  upload-path: D:\img\

